runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /(.*\.css)
  mime_type: text/css
  static_files: \1
  upload: (.*\.css)

- url: /(.*\.htc)
  mime_type: text/x-component
  static_files: \1
  upload: (.*\.htc)

- url: /(.*\.html)
  mime_type: text/html
  static_files: \1
  upload: (.*\.html)
  secure: always
  expiration: "1h"

- url: /(.*\.htm)
  mime_type: text/html
  static_files: \1
  upload: (.*\.htm)
  secure: always
  expiration: "1h"

- url: /(.*\.ico)
  mime_type: image/x-icon
  static_files: \1
  upload: (.*\.ico)
  expiration: "7d"

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: \1
  upload: (.*\.js)

- url: /(.*\.rss)
  mime_type: application/rss+xml
  static_files: \1
  upload: (.*\.rss)
  expiration: "1h"

- url: /(.*\.swf)
  mime_type: application/x-shockwave-flash
  static_files: \1
  upload: (.*\.swf)

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: \1
  upload: (.*\.txt)

- url: /(.*\.xml)
  mime_type: application/xml
  static_files: \1
  upload: (.*\.xml)
  expiration: "1h"

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: \1
  upload: (.*\.(bmp|gif|ico|jpeg|jpg|png))

# audio files
- url: /(.*\.(mid|midi|mp3|wav))
  static_files: \1
  upload: (.*\.(mid|midi|mp3|wav))  

# windows files
- url: /(.*\.(doc|ppt|rtf|xls))
  static_files: \1
  upload: (.*\.(doc|ppt|rtf|xls))

# compressed files
- url: /(.*\.(bz2|gz|rar|tar|tgz|zip))
  static_files: \1
  upload: (.*\.(bz2|gz|rar|tar|tgz|zip))

# kmz files
- url: /(.*\.kmz)
  mime_type: application/vnd.google-earth.kml+xml
  static_files: \1
  upload: (.*\.kmz)

# kmz files
- url: /(.*\.kml)
  mime_type: application/vnd.google-earth.kml+xml
  static_files: \1
  upload: (.*\.kml)

# index files
- url: /(.+)/
  static_files: \1/index.html
  upload: (.+)/index.html
  secure: always
  expiration: "15m"

- url: /(.*)/
  static_files: \1/index.html
  upload: (.*)/index.html
  secure: always

# site root
- url: /
  static_files: index.html
  upload: index.html
  secure: always
  expiration: "15m"